// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1zRH6FjD9QyKLE1TQWOZP-HOV3t8sv_M',
    appId: '1:965002991981:web:ba0da42328b055e3bb2264',
    messagingSenderId: '965002991981',
    projectId: 'mylez-gidah-project',
    authDomain: 'mylez-gidah-project.firebaseapp.com',
    storageBucket: 'mylez-gidah-project.appspot.com',
    measurementId: 'G-PPY3YR2JKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-gGGIekyO8f7_y0E6GLlpBXqBCPXQ504',
    appId: '1:965002991981:android:7eff87ea8f0c147bbb2264',
    messagingSenderId: '965002991981',
    projectId: 'mylez-gidah-project',
    storageBucket: 'mylez-gidah-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJtz97kttUbVTbAnyiyS-9EhkYDLANlM',
    appId: '1:965002991981:ios:ed481f6af00054b9bb2264',
    messagingSenderId: '965002991981',
    projectId: 'mylez-gidah-project',
    storageBucket: 'mylez-gidah-project.appspot.com',
    iosBundleId: 'com.example.gidah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDJtz97kttUbVTbAnyiyS-9EhkYDLANlM',
    appId: '1:965002991981:ios:1a1982d96bbaca27bb2264',
    messagingSenderId: '965002991981',
    projectId: 'mylez-gidah-project',
    storageBucket: 'mylez-gidah-project.appspot.com',
    iosBundleId: 'com.example.gidah.RunnerTests',
  );
}